# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jack/Documents/repos/serene

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jack/Documents/repos/serene

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Documents/repos/serene/CMakeFiles /home/jack/Documents/repos/serene//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/Documents/repos/serene/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named serene

# Build rule for target.
serene: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serene
.PHONY : serene

# fast build rule for target.
serene/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serene.dir/build.make CMakeFiles/serene.dir/build
.PHONY : serene/fast

lib/engine/app_searcher.o: lib/engine/app_searcher.cpp.o
.PHONY : lib/engine/app_searcher.o

# target to build an object file
lib/engine/app_searcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/app_searcher.cpp.o
.PHONY : lib/engine/app_searcher.cpp.o

lib/engine/app_searcher.i: lib/engine/app_searcher.cpp.i
.PHONY : lib/engine/app_searcher.i

# target to preprocess a source file
lib/engine/app_searcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/app_searcher.cpp.i
.PHONY : lib/engine/app_searcher.cpp.i

lib/engine/app_searcher.s: lib/engine/app_searcher.cpp.s
.PHONY : lib/engine/app_searcher.s

# target to generate assembly for a file
lib/engine/app_searcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/app_searcher.cpp.s
.PHONY : lib/engine/app_searcher.cpp.s

lib/engine/engine.o: lib/engine/engine.cpp.o
.PHONY : lib/engine/engine.o

# target to build an object file
lib/engine/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/engine.cpp.o
.PHONY : lib/engine/engine.cpp.o

lib/engine/engine.i: lib/engine/engine.cpp.i
.PHONY : lib/engine/engine.i

# target to preprocess a source file
lib/engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/engine.cpp.i
.PHONY : lib/engine/engine.cpp.i

lib/engine/engine.s: lib/engine/engine.cpp.s
.PHONY : lib/engine/engine.s

# target to generate assembly for a file
lib/engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/engine.cpp.s
.PHONY : lib/engine/engine.cpp.s

lib/engine/file_searcher.o: lib/engine/file_searcher.cpp.o
.PHONY : lib/engine/file_searcher.o

# target to build an object file
lib/engine/file_searcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/file_searcher.cpp.o
.PHONY : lib/engine/file_searcher.cpp.o

lib/engine/file_searcher.i: lib/engine/file_searcher.cpp.i
.PHONY : lib/engine/file_searcher.i

# target to preprocess a source file
lib/engine/file_searcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/file_searcher.cpp.i
.PHONY : lib/engine/file_searcher.cpp.i

lib/engine/file_searcher.s: lib/engine/file_searcher.cpp.s
.PHONY : lib/engine/file_searcher.s

# target to generate assembly for a file
lib/engine/file_searcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/file_searcher.cpp.s
.PHONY : lib/engine/file_searcher.cpp.s

lib/engine/hybrid_file_searcher.o: lib/engine/hybrid_file_searcher.cpp.o
.PHONY : lib/engine/hybrid_file_searcher.o

# target to build an object file
lib/engine/hybrid_file_searcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/hybrid_file_searcher.cpp.o
.PHONY : lib/engine/hybrid_file_searcher.cpp.o

lib/engine/hybrid_file_searcher.i: lib/engine/hybrid_file_searcher.cpp.i
.PHONY : lib/engine/hybrid_file_searcher.i

# target to preprocess a source file
lib/engine/hybrid_file_searcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/hybrid_file_searcher.cpp.i
.PHONY : lib/engine/hybrid_file_searcher.cpp.i

lib/engine/hybrid_file_searcher.s: lib/engine/hybrid_file_searcher.cpp.s
.PHONY : lib/engine/hybrid_file_searcher.s

# target to generate assembly for a file
lib/engine/hybrid_file_searcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/lib/engine/hybrid_file_searcher.cpp.s
.PHONY : lib/engine/hybrid_file_searcher.cpp.s

src/components/customsearchentry.o: src/components/customsearchentry.cpp.o
.PHONY : src/components/customsearchentry.o

# target to build an object file
src/components/customsearchentry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/customsearchentry.cpp.o
.PHONY : src/components/customsearchentry.cpp.o

src/components/customsearchentry.i: src/components/customsearchentry.cpp.i
.PHONY : src/components/customsearchentry.i

# target to preprocess a source file
src/components/customsearchentry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/customsearchentry.cpp.i
.PHONY : src/components/customsearchentry.cpp.i

src/components/customsearchentry.s: src/components/customsearchentry.cpp.s
.PHONY : src/components/customsearchentry.s

# target to generate assembly for a file
src/components/customsearchentry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/customsearchentry.cpp.s
.PHONY : src/components/customsearchentry.cpp.s

src/components/itemdetails.o: src/components/itemdetails.cpp.o
.PHONY : src/components/itemdetails.o

# target to build an object file
src/components/itemdetails.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/itemdetails.cpp.o
.PHONY : src/components/itemdetails.cpp.o

src/components/itemdetails.i: src/components/itemdetails.cpp.i
.PHONY : src/components/itemdetails.i

# target to preprocess a source file
src/components/itemdetails.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/itemdetails.cpp.i
.PHONY : src/components/itemdetails.cpp.i

src/components/itemdetails.s: src/components/itemdetails.cpp.s
.PHONY : src/components/itemdetails.s

# target to generate assembly for a file
src/components/itemdetails.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/itemdetails.cpp.s
.PHONY : src/components/itemdetails.cpp.s

src/components/listview.o: src/components/listview.cpp.o
.PHONY : src/components/listview.o

# target to build an object file
src/components/listview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/listview.cpp.o
.PHONY : src/components/listview.cpp.o

src/components/listview.i: src/components/listview.cpp.i
.PHONY : src/components/listview.i

# target to preprocess a source file
src/components/listview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/listview.cpp.i
.PHONY : src/components/listview.cpp.i

src/components/listview.s: src/components/listview.cpp.s
.PHONY : src/components/listview.s

# target to generate assembly for a file
src/components/listview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/listview.cpp.s
.PHONY : src/components/listview.cpp.s

src/components/scrollview.o: src/components/scrollview.cpp.o
.PHONY : src/components/scrollview.o

# target to build an object file
src/components/scrollview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/scrollview.cpp.o
.PHONY : src/components/scrollview.cpp.o

src/components/scrollview.i: src/components/scrollview.cpp.i
.PHONY : src/components/scrollview.i

# target to preprocess a source file
src/components/scrollview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/scrollview.cpp.i
.PHONY : src/components/scrollview.cpp.i

src/components/scrollview.s: src/components/scrollview.cpp.s
.PHONY : src/components/scrollview.s

# target to generate assembly for a file
src/components/scrollview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/components/scrollview.cpp.s
.PHONY : src/components/scrollview.cpp.s

src/core/main.o: src/core/main.cpp.o
.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serene.dir/build.make CMakeFiles/serene.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i
.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serene.dir/build.make CMakeFiles/serene.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s
.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serene.dir/build.make CMakeFiles/serene.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

src/core/serene.o: src/core/serene.cpp.o
.PHONY : src/core/serene.o

# target to build an object file
src/core/serene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/core/serene.cpp.o
.PHONY : src/core/serene.cpp.o

src/core/serene.i: src/core/serene.cpp.i
.PHONY : src/core/serene.i

# target to preprocess a source file
src/core/serene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/core/serene.cpp.i
.PHONY : src/core/serene.cpp.i

src/core/serene.s: src/core/serene.cpp.s
.PHONY : src/core/serene.s

# target to generate assembly for a file
src/core/serene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/core/serene.cpp.s
.PHONY : src/core/serene.cpp.s

src/models/applicationobject.o: src/models/applicationobject.cpp.o
.PHONY : src/models/applicationobject.o

# target to build an object file
src/models/applicationobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/applicationobject.cpp.o
.PHONY : src/models/applicationobject.cpp.o

src/models/applicationobject.i: src/models/applicationobject.cpp.i
.PHONY : src/models/applicationobject.i

# target to preprocess a source file
src/models/applicationobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/applicationobject.cpp.i
.PHONY : src/models/applicationobject.cpp.i

src/models/applicationobject.s: src/models/applicationobject.cpp.s
.PHONY : src/models/applicationobject.s

# target to generate assembly for a file
src/models/applicationobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/applicationobject.cpp.s
.PHONY : src/models/applicationobject.cpp.s

src/models/combinedlistmodel.o: src/models/combinedlistmodel.cpp.o
.PHONY : src/models/combinedlistmodel.o

# target to build an object file
src/models/combinedlistmodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/combinedlistmodel.cpp.o
.PHONY : src/models/combinedlistmodel.cpp.o

src/models/combinedlistmodel.i: src/models/combinedlistmodel.cpp.i
.PHONY : src/models/combinedlistmodel.i

# target to preprocess a source file
src/models/combinedlistmodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/combinedlistmodel.cpp.i
.PHONY : src/models/combinedlistmodel.cpp.i

src/models/combinedlistmodel.s: src/models/combinedlistmodel.cpp.s
.PHONY : src/models/combinedlistmodel.s

# target to generate assembly for a file
src/models/combinedlistmodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/combinedlistmodel.cpp.s
.PHONY : src/models/combinedlistmodel.cpp.s

src/models/fileobject.o: src/models/fileobject.cpp.o
.PHONY : src/models/fileobject.o

# target to build an object file
src/models/fileobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/fileobject.cpp.o
.PHONY : src/models/fileobject.cpp.o

src/models/fileobject.i: src/models/fileobject.cpp.i
.PHONY : src/models/fileobject.i

# target to preprocess a source file
src/models/fileobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/fileobject.cpp.i
.PHONY : src/models/fileobject.cpp.i

src/models/fileobject.s: src/models/fileobject.cpp.s
.PHONY : src/models/fileobject.s

# target to generate assembly for a file
src/models/fileobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/models/fileobject.cpp.s
.PHONY : src/models/fileobject.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... common"
	@echo "... serene"
	@echo "... lib/engine/app_searcher.o"
	@echo "... lib/engine/app_searcher.i"
	@echo "... lib/engine/app_searcher.s"
	@echo "... lib/engine/engine.o"
	@echo "... lib/engine/engine.i"
	@echo "... lib/engine/engine.s"
	@echo "... lib/engine/file_searcher.o"
	@echo "... lib/engine/file_searcher.i"
	@echo "... lib/engine/file_searcher.s"
	@echo "... lib/engine/hybrid_file_searcher.o"
	@echo "... lib/engine/hybrid_file_searcher.i"
	@echo "... lib/engine/hybrid_file_searcher.s"
	@echo "... src/components/customsearchentry.o"
	@echo "... src/components/customsearchentry.i"
	@echo "... src/components/customsearchentry.s"
	@echo "... src/components/itemdetails.o"
	@echo "... src/components/itemdetails.i"
	@echo "... src/components/itemdetails.s"
	@echo "... src/components/listview.o"
	@echo "... src/components/listview.i"
	@echo "... src/components/listview.s"
	@echo "... src/components/scrollview.o"
	@echo "... src/components/scrollview.i"
	@echo "... src/components/scrollview.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/core/serene.o"
	@echo "... src/core/serene.i"
	@echo "... src/core/serene.s"
	@echo "... src/models/applicationobject.o"
	@echo "... src/models/applicationobject.i"
	@echo "... src/models/applicationobject.s"
	@echo "... src/models/combinedlistmodel.o"
	@echo "... src/models/combinedlistmodel.i"
	@echo "... src/models/combinedlistmodel.s"
	@echo "... src/models/fileobject.o"
	@echo "... src/models/fileobject.i"
	@echo "... src/models/fileobject.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

